server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: gp-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.gp.**.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: delFlag
      logic-delete-value: '2'
      logic-not-delete-value: '0'

# Knife4j
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
knife4j:
  enable: true
  setting:
    language: zh_cn

# JWT
gp:
  jwt:
    secret: gpFrameworkSecretKey2024GPFrameworkForGraduationProject
    expire-time: 30
